version: "3.3"
services:
  nexus:
    image: sonatype/nexus3:3.66.0
    container_name: nexus
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    volumes:
      - ./config/nexus.properties:/nexus-data/etc/nexus.properties
      - /data/nexus-data:/nexus-data
    ports:
      - 8081-8100:8081-8100
    restart: unless-stopped
